### ISSUE TITLE
Stalling in 3-stage SODOR

### ISSUE THREAD

**Issue by zwabbit** [ucb-bar/riscv-sodor#14]
I just wanted to clarify something, looking at the 3-stage SODOR source code I see stalling present for data hazards, but nothing that seems to respond to memory. Am I correct in assuming that SODOR assumes a single cycle response for memory operations or something therein?

**Comment by ccelio** [comment]
Hopefully the opening section of the README addresses your question:

> All processors talk to a simple scratchpad memory (asynchronous, single-cycle), with no backing outer memory (the 3-stage is the exception - its scratchpad is synchronous). Programs are loaded in via a Host-target Interface (HTIF) port (while the core is kept in reset), effectively making the scratchpads 3-port memories (instruction, data, HTIF).

So yes, it's assumed it is talking to a single-cycle "scratchpad" memory, not a cache.  Let me know if you have any other questions!
