### ISSUE TITLE
elf2hex usage with sodor ( assertion `taddr < width*depth' failed )

### ISSUE THREAD

**Issue by ksh12** [ucb-bar/riscv-sodor#16]
I am trying to use elf2hex utility on a host ( little endian x86_64).
In the riscv-sodor/riscv-tests/benchmarks

I do:

make riscv

Then i try to convert the dhrystone.riscv ( generated by riscv32-unknown-elf-gcc ) to hex :

elf2hex 16 32768 dhrystone.riscv

i get : 

```
elf2hex: ./fesvr/htif_hexwriter.cc:16: virtual void htif_hexwriter_t::read_chunk(addr_t, size_t, void*): Assertion `taddr < width*depth` failed.
```

I also tried other width and length but i always get this assertion.

Can someone please let me know what can be the issue.

**Comment by ccelio** [comment]
As `16 32768` appears to be the correct arguments (https://github.com/riscv/riscv-tests/blob/fc000796c11f84a5e1997c67fcfac751aa64a916/benchmarks/Makefile#L78, the best direction I can give you, aside from trying other inputs, is to look through the code and see if it's clear what that assertion is guarding against.

**Comment by hauhsu** [comment]
I had the same issue earlier. I found it is because the link script place the code from 0x80000000.
After modifying it to 0x200, it works fine.

**Comment by susi655** [comment]
Similar issue for me also.
It is coming when I am changing Origin of imem from 0x80000000 to 0x00000000 in .ld file(linker command file).
[error.txt](https://github.com/ucb-bar/riscv-sodor/files/951459/error.txt)

**Comment by codelec** [comment]
elf2hex is not needed anymore so this issue could be closed

**Comment by Strange21** [comment]
@codelec Can you please describe what tools to be used? if elf2hex is not needed any more.
I am stuck at similar issue where I am changing my start location from 0x80000000 --> 0x80100000, & this tool is throwing same error.

**Comment by codelec** [comment]
we were using SimDTM (through patched riscv-fesvr) when elf2hex was removed
