### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by samiasd** [ucb-bar/riscv-sodor#17]
Dear Sodor Team,
I'm working to test sodor processor for some work, and I got the following error when I tried to compile the tests,,,, in order to write a new test for me

/riscv-sodor/riscv-tests/isa$ make
riscv32-unknown-elf-gcc -m32  -DENTROPY=7542 -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -I./../env/p -I./macros/scalar -T./../env/p/link.ld rv32ui/simple.S -o rv32ui-p-simple
rv32ui/simple.S: Assembler messages:
rv32ui/simple.S:16: Error: unrecognized opcode `mrts'
rv32ui/simple.S:16: Error: Instruction csrw requires absolute expression
rv32ui/simple.S:16: Error: Instruction csrr requires absolute expression
rv32ui/simple.S:16: Error: unrecognized opcode `eret'
make: *** [rv32ui-p-simple] Error 1

can you please advice??

**Comment by ccelio** [comment]
Your toolchain is out-of-version with the version of riscv-tests that Sodor points to. I recommend you change your riscv-tools version to a date near the commit used by riscv-tests.  I haven't updated Sodor to the latest privilege spec stuff in part because I am waiting for it to settle down.
