### ISSUE TITLE
The encoding of stall instruction is incorrect in the emulator

### ISSUE THREAD

**Issue by yanyh15** [ucb-bar/riscv-sodor#18]
The stall instruction used (XOR x0 x0 x0) is encoded as 0x4033, however, in trace.c and bp.cpp, 0x5033 is used (which is also no-ops). it however causes the incorrect summary output for Bubbles percentage in examples such as output/vvadd.riscv.out.

To fix: change 5033 to 4033 in trace.c and bp.cpp

**Comment by yanyh15** [comment]
Bug fix in https://github.com/passlab/riscv-sodor

**Comment by ccelio** [comment]
Closed by #19. Thanks for the bug report and fix!
