### ISSUE TITLE
syntax errors while building

### ISSUE THREAD

**Issue by jbaramidze** [ucb-bar/riscv-sodor#22]
Hello,

I'm trying to build according instructions and I get following errors:

`g++  -O1 -std=c++11  -g -I/home/zhani/riscv-sodor/emulator/common -I/usr/local/include -Igenerated-src -c -o htif_emulator.o /home/zhani/riscv-sodor/emulator/common/htif_emulator.cc

In file included from /home/zhani/riscv-sodor/emulator/common/htif_emulator.cc:1:0:
/home/zhani/riscv-sodor/emulator/common/htif_emulator.h: In constructor ‘htif_emulator_t::htif_emulator_t(uint64_t, const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/zhani/riscv-sodor/emulator/common/htif_emulator.h:19:32: error: ‘assert’ was not declared in this scope
       assert ((memsz >> 20) > 0);
                                ^

/home/zhani/riscv-sodor/emulator/common/htif_emulator.h: In member function ‘void htif_emulator_t::set_clock_divisor(int, int)’:
/home/zhani/riscv-sodor/emulator/common/htif_emulator.h:24:51: error: ‘write_cr’ was not declared in this scope
       write_cr(-1, 63, divisor | hold_cycles << 16);
                                                   ^

/home/zhani/riscv-sodor/emulator/common/htif_emulator.cc: In member function ‘void htif_emulator_t::tick(bool, bool, bool, uint64_t, bool, uint64_t)’:
/home/zhani/riscv-sodor/emulator/common/htif_emulator.cc:41:7: error: ‘packet_header_t’ was not declared in this scope
       packet_header_t ack(HTIF_CMD_ACK, seqno, 1, 0);
       ^
`

I grepped write_cr and it's only found at that 1 location, how is this supposed to compile?

**Comment by codelec** [comment]
@jbaramidze could you please try it again with the latest changes and also a minor change as mentioned here #29

**Comment by donggyukim** [comment]
We don't have `htif_emulator.cc` any more, so it is closed.
