### ISSUE TITLE
Bug in 3-stage ALU sltu instruction?

### ISSUE THREAD

**Issue by pete678** [ucb-bar/riscv-sodor#24]
It seems that the isSLTU function checks if the least significant bit is set to distinguish between SLT and SLTU. However, they are encoded as 12 and 14 respectively, so SLTU is executed as SLT. Checking bit 1 instead would seem to fix this?

**Comment by codelec** [comment]
Hey @pete678 that issue will be fixed soon once the pull request #23 get's merged 
https://github.com/librecores/riscv-sodor/blob/master/src/rv32_3stage/alu.scala

**Comment by ccelio** [comment]
#23 has been merged. Thanks guys.
