### ISSUE TITLE
How to compile the tracer?

### ISSUE THREAD

**Issue by MahdiNazemi** [ucb-bar/riscv-sodor#28]
I was looking at the `emulator/common/Makefile.include` and it turns out that the code for building the tracer is commented out. Additionally, it looks like `tracer.cpp` includes `"emulator.h"` which I couldn't find in the source code. Would you please let me know how I can build the tracer so that I can get the trace information in the outputs?

**Comment by ccelio** [comment]
The tracer stuff is fully deprecated -- it was C++ code that hooked into the C++ testharness designed for students who were familiar with C++. But trying to hook into the RTL signals via C++ code was just too hacky and fragile.

Going forward, I believe the best option is to move the tracer stuff into Chisel so it is synthesizable.

**Comment by MahdiNazemi** [comment]
Thanks for your explanation. I will issue a pull request in case I implement a tracer in Chisel, so that it can be integrated in the tool.
