### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by zhpzhp** [ucb-bar/riscv-sodor#31]
Hi, when I try to build the sodor emulator, there are some errors. How can I solve it?

[info] [0.001] Elaborating design...

    Sodor Tile: creating Asynchronous Scratchpad Memory of size 2048 kB

[info] [0.425] Done elaborating.
[error] (run-main) firrtl.passes.PassExceptions: 
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.versionhi <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
[error]    : abstractcsReset.reserved0 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.sbaccess128 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
[error]    : abstractcsReset.reserved3 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    : io.debugmem.req.bits.typ <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    @[debug.scala 203:50:@270.6] : node _GEN_24 = mux(_T_238, sbaddr, VOID) @[debug.scala 203:50:@270.6]
[error]    @[debug.scala 169:54:@149.4] : node _GEN_49 = mux(_T_302, _GEN_24, VOID) @[debug.scala 169:54:@149.4]
[error]    @[debug.scala 240:137:@322.4] : node _GEN_65 = mux(_T_390, sbaddr, _GEN_49) @[debug.scala 240:137:@322.4]
[error]    : io.debugmem.req.bits.addr <= _GEN_65
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    @[debug.scala 222:24:@298.6] : node _GEN_57 = mux(command.write, UInt<1>("h1"), VOID) @[debug.scala 222:24:@298.6]
[error]    @[debug.scala 221:54:@297.4] : node _GEN_60 = mux(_T_373, _GEN_57, VOID) @[debug.scala 221:54:@297.4]
[error]    : io.ddpath.validreq <= _GEN_60
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.sbsingleread <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.allrunning <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.allresumeack <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.allunavail <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.anynonexistent <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.anyhalted <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
[error]    : abstractcsReset.reserved2 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.anyrunning <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    @[debug.scala 203:50:@270.6] : node _GEN_25 = mux(_T_238, sbdata, VOID) @[debug.scala 203:50:@270.6]
[error]    @[debug.scala 169:54:@149.4] : node _GEN_50 = mux(_T_302, _GEN_25, VOID) @[debug.scala 169:54:@149.4]
[error]    : io.debugmem.req.bits.data <= _GEN_50
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.sbautoread <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    @[debug.scala 203:50:@270.6] : node _GEN_27 = mux(_T_238, io.dmi.req.valid, VOID) @[debug.scala 203:50:@270.6]
[error]    @[debug.scala 169:54:@149.4] : node _GEN_52 = mux(_T_302, _GEN_27, VOID) @[debug.scala 169:54:@149.4]
[error]    @[debug.scala 240:137:@322.4] : node _GEN_67 = mux(_T_390, io.dmi.req.valid, _GEN_52) @[debug.scala 240:137:@322.4]
[error]    : io.debugmem.req.valid <= _GEN_67
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.sberror <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    @[debug.scala 203:50:@270.6] : node _GEN_26 = mux(_T_238, UInt<1>("h1"), VOID) @[debug.scala 203:50:@270.6]
[error]    @[debug.scala 169:54:@149.4] : node _GEN_51 = mux(_T_302, _GEN_26, VOID) @[debug.scala 169:54:@149.4]
[error]    @[debug.scala 231:98:@310.4] : node _GEN_63 = mux(_T_380, UInt<1>("h0"), _GEN_51) @[debug.scala 231:98:@310.4]
[error]    @[debug.scala 240:137:@322.4] : node _GEN_66 = mux(_T_390, UInt<1>("h0"), _GEN_63) @[debug.scala 240:137:@322.4]
[error]    : io.debugmem.req.bits.fcn <= _GEN_66
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.reserved1 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.cfgstrvalid <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.anyunavail <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    @[debug.scala 222:24:@298.6] : node _GEN_56 = mux(command.write, data0, VOID) @[debug.scala 222:24:@298.6]
[error]    @[debug.scala 221:54:@297.4] : node _GEN_59 = mux(_T_373, _GEN_56, VOID) @[debug.scala 221:54:@297.4]
[error]    : io.ddpath.wdata <= _GEN_59
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.allnonexistent <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.sbaccess64 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
[error]    : abstractcsReset.cmderr <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
[error]    : abstractcsReset.reserved1 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.reserved0 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
[error]    : io.ddpath.resetpc <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.authbusy <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.allhalted <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.anyresumeack <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
[error]    : abstractcsReset.busy <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
[error]    : sbcsreset.sbautoincrement <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
[error]    : dmstatusReset.reserved0 <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
[error]    : io.dmem.req.bits.addr <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
[error]    : io.imem.req.bits.addr <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
[error]    : io.dmem.req.bits.data <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
[error]    : io.imem.req.bits.data <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@1074.4] : [module CSRFile]  Reference io is not fully initialized.
[error]    : io.singleStep <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@1074.4] : [module CSRFile]  Reference io is not fully initialized.
[error]    @[csr.scala 284:23:@1897.4] : node _GEN_3 = mux(io.exception, UInt<32>("h80000004"), VOID) @[csr.scala 284:23:@1897.4]
[error]    @[csr.scala 297:38:@1917.4] : node _GEN_8 = mux(_T_974, reg_dpc, _GEN_3) @[csr.scala 297:38:@1917.4]
[error]    @[csr.scala 304:41:@1925.4] : node _GEN_12 = mux(_T_979, reg_mepc, _GEN_8) @[csr.scala 304:41:@1925.4]
[error]    @[csr.scala 312:18:@1931.4] : node _GEN_13 = mux(insn_call, UInt<32>("h80000004"), _GEN_12) @[csr.scala 312:18:@1931.4]
[error]    @[csr.scala 318:19:@1937.4] : node _GEN_15 = mux(insn_break, UInt<32>("h80000004"), _GEN_13) @[csr.scala 318:19:@1937.4]
[error]    : io.evec <= _GEN_15
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
[error]    : io.dmem.req.bits.typ <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
[error]    : io.dmem.req.valid <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
[error]    : io.dmem.req.bits.fcn <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
[error]    : io.imem.req.bits.fcn <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
[error]    : io.imem.req.bits.typ <= VOID
[error] firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
[error]    : io.imem.req.bits.data <= VOID
[error] firrtl.passes.PassException: 48 errors detected!
firrtl.passes.PassExceptions: 
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.versionhi <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
   : abstractcsReset.reserved0 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.sbaccess128 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
   : abstractcsReset.reserved3 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   : io.debugmem.req.bits.typ <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   @[debug.scala 203:50:@270.6] : node _GEN_24 = mux(_T_238, sbaddr, VOID) @[debug.scala 203:50:@270.6]
   @[debug.scala 169:54:@149.4] : node _GEN_49 = mux(_T_302, _GEN_24, VOID) @[debug.scala 169:54:@149.4]
   @[debug.scala 240:137:@322.4] : node _GEN_65 = mux(_T_390, sbaddr, _GEN_49) @[debug.scala 240:137:@322.4]
   : io.debugmem.req.bits.addr <= _GEN_65
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   @[debug.scala 222:24:@298.6] : node _GEN_57 = mux(command.write, UInt<1>("h1"), VOID) @[debug.scala 222:24:@298.6]
   @[debug.scala 221:54:@297.4] : node _GEN_60 = mux(_T_373, _GEN_57, VOID) @[debug.scala 221:54:@297.4]
   : io.ddpath.validreq <= _GEN_60
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.sbsingleread <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.allrunning <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.allresumeack <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.allunavail <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.anynonexistent <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.anyhalted <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
   : abstractcsReset.reserved2 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.anyrunning <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   @[debug.scala 203:50:@270.6] : node _GEN_25 = mux(_T_238, sbdata, VOID) @[debug.scala 203:50:@270.6]
   @[debug.scala 169:54:@149.4] : node _GEN_50 = mux(_T_302, _GEN_25, VOID) @[debug.scala 169:54:@149.4]
   : io.debugmem.req.bits.data <= _GEN_50
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.sbautoread <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   @[debug.scala 203:50:@270.6] : node _GEN_27 = mux(_T_238, io.dmi.req.valid, VOID) @[debug.scala 203:50:@270.6]
   @[debug.scala 169:54:@149.4] : node _GEN_52 = mux(_T_302, _GEN_27, VOID) @[debug.scala 169:54:@149.4]
   @[debug.scala 240:137:@322.4] : node _GEN_67 = mux(_T_390, io.dmi.req.valid, _GEN_52) @[debug.scala 240:137:@322.4]
   : io.debugmem.req.valid <= _GEN_67
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.sberror <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   @[debug.scala 203:50:@270.6] : node _GEN_26 = mux(_T_238, UInt<1>("h1"), VOID) @[debug.scala 203:50:@270.6]
   @[debug.scala 169:54:@149.4] : node _GEN_51 = mux(_T_302, _GEN_26, VOID) @[debug.scala 169:54:@149.4]
   @[debug.scala 231:98:@310.4] : node _GEN_63 = mux(_T_380, UInt<1>("h0"), _GEN_51) @[debug.scala 231:98:@310.4]
   @[debug.scala 240:137:@322.4] : node _GEN_66 = mux(_T_390, UInt<1>("h0"), _GEN_63) @[debug.scala 240:137:@322.4]
   : io.debugmem.req.bits.fcn <= _GEN_66
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.reserved1 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.cfgstrvalid <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.anyunavail <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   @[debug.scala 222:24:@298.6] : node _GEN_56 = mux(command.write, data0, VOID) @[debug.scala 222:24:@298.6]
   @[debug.scala 221:54:@297.4] : node _GEN_59 = mux(_T_373, _GEN_56, VOID) @[debug.scala 221:54:@297.4]
   : io.ddpath.wdata <= _GEN_59
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.allnonexistent <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.sbaccess64 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
   : abstractcsReset.cmderr <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
   : abstractcsReset.reserved1 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.reserved0 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@6.4] : [module DebugModule]  Reference io is not fully initialized.
   : io.ddpath.resetpc <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.authbusy <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.allhalted <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.anyresumeack <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 128:29:@21.4] : [module DebugModule]  Reference abstractcsReset is not fully initialized.
   : abstractcsReset.busy <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 121:23:@14.4] : [module DebugModule]  Reference sbcsreset is not fully initialized.
   : sbcsreset.sbautoincrement <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[debug.scala 117:28:@10.4] : [module DebugModule]  Reference dmstatusReset is not fully initialized.
   : dmstatusReset.reserved0 <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
   : io.dmem.req.bits.addr <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
   : io.imem.req.bits.addr <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
   : io.dmem.req.bits.data <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@356.4] : [module CtlPath]  Reference io is not fully initialized.
   : io.imem.req.bits.data <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@1074.4] : [module CSRFile]  Reference io is not fully initialized.
   : io.singleStep <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@1074.4] : [module CSRFile]  Reference io is not fully initialized.
   @[csr.scala 284:23:@1897.4] : node _GEN_3 = mux(io.exception, UInt<32>("h80000004"), VOID) @[csr.scala 284:23:@1897.4]
   @[csr.scala 297:38:@1917.4] : node _GEN_8 = mux(_T_974, reg_dpc, _GEN_3) @[csr.scala 297:38:@1917.4]
   @[csr.scala 304:41:@1925.4] : node _GEN_12 = mux(_T_979, reg_mepc, _GEN_8) @[csr.scala 304:41:@1925.4]
   @[csr.scala 312:18:@1931.4] : node _GEN_13 = mux(insn_call, UInt<32>("h80000004"), _GEN_12) @[csr.scala 312:18:@1931.4]
   @[csr.scala 318:19:@1937.4] : node _GEN_15 = mux(insn_break, UInt<32>("h80000004"), _GEN_13) @[csr.scala 318:19:@1937.4]
   : io.evec <= _GEN_15
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
   : io.dmem.req.bits.typ <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
   : io.dmem.req.valid <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
   : io.dmem.req.bits.fcn <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
   : io.imem.req.bits.fcn <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
   : io.imem.req.bits.typ <= VOID
firrtl.passes.CheckInitialization$RefNotInitializedException:  @[:@2698.4] : [module DatPath]  Reference io is not fully initialized.
   : io.imem.req.bits.data <= VOID
firrtl.passes.PassException: 48 errors detected!
	at firrtl.passes.Errors.trigger(Passes.scala:45)
	at firrtl.passes.CheckInitialization$.run(CheckInitialization.scala:92)
	at firrtl.passes.Pass$class.execute(Passes.scala:24)
	at firrtl.passes.CheckInitialization$.execute(CheckInitialization.scala:17)
	at firrtl.Transform$$anonfun$4.apply(Compiler.scala:201)
	at firrtl.Transform$$anonfun$4.apply(Compiler.scala:201)
	at firrtl.Utils$.time(Utils.scala:135)
	at firrtl.Transform.runTransform(Compiler.scala:201)
	at firrtl.SeqTransformBased$$anonfun$runTransforms$1.apply(Compiler.scala:253)
	at firrtl.SeqTransformBased$$anonfun$runTransforms$1.apply(Compiler.scala:253)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at firrtl.SeqTransformBased$class.runTransforms(Compiler.scala:253)
	at firrtl.SeqTransform.runTransforms(Compiler.scala:257)
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1628)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:1628)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:1628)
	at sbt.Defaults$.toError(Defaults.scala:34)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:647)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$36$$anonfun$apply$37.apply(Defaults.scala:645)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[error] (rv32_1stage/compile:run) Nonzero exit code: 1
[error] Total time: 38 s, completed Dec 8, 2017 10:33:23 PM
/home/zhpzhp/riscv-sodor/emulator/common/Makefile.include:80: recipe for target 'generated-src/Top.v' failed
make[1]: *** [generated-src/Top.v] Error 1
make[1]: Leaving directory '/home/zhpzhp/riscv-sodor/emulator/rv32_1stage'
Makefile:108: recipe for target 'emulator/rv32_1stage/emulator' failed
make: *** [emulator/rv32_1stage/emulator] Error 2

**Comment by codelec** [comment]
@zhpzhp #30 fix for this is coming up. For now could you please try this clone https://github.com/librecores/riscv-sodor

**Comment by donggyukim** [comment]
Fixed by #33.
