### ISSUE TITLE
make run-emulator error

### ISSUE THREAD

**Issue by ictzhanglei** [ucb-bar/riscv-sodor#6]
I am using g++-4.9.2 in ubuntu 12.04, and encounter the following Error 120 when try make run-emulator. There are no more hint on what the problems are? Any one can help?
==================================
./emulator +max-cycles=30000  +verbose +coremap-random +loadmem=output/simple.hex none 2> output/simple.out
make[1]: [output/simple.out] Error 120 (ignored)
./emulator +max-cycles=30000  +verbose +coremap-random +loadmem=output/add.hex none 2> output/add.out
make[1]: [output/add.out] Error 120 (ignored)
./emulator +max-cycles=30000  +verbose +coremap-random +loadmem=output/addi.hex none 2> output/addi.out
make[1]: [output/addi.out] Error 120 (ignored)
....

**Comment by ccelio** [comment]
You need to look at the output files and see what's in them.

**Comment by ictzhanglei** [comment]
The outputs say:

Loaded memory.
Instantiated HTIF.
*** FAILED *** (tohost = 56679288)

no else.

**Comment by ccelio** [comment]
I have made significant changes to the structure of Sodor and updated the cores to the latest Privileged ISA v1.7 (at least, the 1-stage, 2-stage, and 3-stage. The 5-stage and u-code are turned off for now).

Please try again and re-submit a new issue if your problems still persist.
