### ISSUE TITLE
No emulator directory??

### ISSUE THREAD

**Issue by Kian75** [ucb-bar/riscv-sodor#64]
Hi... 
My question cab be a really silly one but there is no emulator directory anymore in this repo.... So how can I make those rv32 cores that you have in src/main/scala directory?

**Comment by Tianhang-Cheng** [comment]
I also don't know how to build the emulator, but I download the emulator file from https://github.com/librecores/riscv-sodor.

**Comment by jerryz123** [comment]
Sodor is now supported in Chipyard. Please see the Chipyard documentation for info on how to run a Sodor simulation
https://chipyard.readthedocs.io/en/latest/index.html
