### ISSUE TITLE
make run-emulator FAILED

### ISSUE THREAD

**Issue by lx324310** [ucb-bar/riscv-sodor#7]
Hi
when i make run-emulator i had pass in rv32_1stage rv32_2stage rv32_5stage but met the follow error in rv32_ucode
make[1]: [output/xori.out] Error 255 (ignored)
  [ FAILED ] output/simple.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/add.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/addi.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/and.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/andi.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/auipc.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/beq.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/bge.out 	 (timeout) after 30000 cycles
  [ FAILED ] output/bgeu.out 	 (timeout) after 30000 cycles
then i checked /emulator/rv32_ucode/output/***.out find
Loaded memory.
Instantiated HTIF.
   Cyc=          0 PCReg=( 0x00000000 ) InstReg=[ 0x00000000 : unknown                    ] UPC=  6 (MA=0x0000eeee)    RegAddr=32 Bus=0x00002000 A=0x0000aaaa B=0x0000bbbb
all PCreg is zero 
how can i solve this problem?

**Comment by huangchengxtu** [comment]
oh！    I also met。

**Comment by ccelio** [comment]
I have made significant changes to the structure of Sodor and updated the cores to the latest Privileged ISA v1.7 (at least, the 1-stage, 2-stage, and 3-stage. The 5-stage and u-code are turned off for now).

Please try again and re-submit a new issue if your problems still persist.
